### ISSUE TITLE
after updating executable permission error

### ISSUE THREAD

**Issue by Itai-Nelken** [spectrumgamer75/All-is-well#7]
I started AIW today, and it updated. but next time I wanted to run it, it didn't have the permission to be executable (probably the wrong way to say it).

I read the code and it should be given executable permission after updating, but it doesn't work...

**Comment by spectrumgamer75** [comment]
I know, have fixed this issue. Please check now

**Comment by spectrumgamer75** [comment]
Have fixed it, please have a look now.

**Comment by Itai-Nelken** [comment]
can you push something to see if its really fixed?

**Comment by spectrumgamer75** [comment]
will add a comment now

**Comment by spectrumgamer75** [comment]
Have added some more comments, check now

**Comment by Itai-Nelken** [comment]
works now! thanks.

**Comment by spectrumgamer75** [comment]
You are welcome :blush:
